In [127]:
using GLPKMathProgInterface
using JuMP

In [128]:
FILE_NAME = "../instances/mdmt39.112.A.ins"

"../instances/mdmt39.112.A.ins"

In [129]:
(M,L,l,d)=open(FILE_NAME) do io
    (M,L,l)=map(split(readline(io))) do x parse(Int,x) end
    (M,L,l,reshape(map(split(readstring(io))) do x parse(x) end,L,M)')
end
println("Size $(M)x$(L), select $l.")

Size 450x450, select 112.


In [88]:
model = Model(solver=GLPKSolverMIP(tm_lim=60000))
@variable(model, x[1:L], Bin)
@variable(model, dist[1:M], Int)

450-element Array{JuMP.Variable,1}:
 dist[1]  
 dist[2]  
 dist[3]  
 dist[4]  
 dist[5]  
 dist[6]  
 dist[7]  
 dist[8]  
 dist[9]  
 dist[10] 
 dist[11] 
 dist[12] 
 dist[13] 
 ⋮        
 dist[439]
 dist[440]
 dist[441]
 dist[442]
 dist[443]
 dist[444]
 dist[445]
 dist[446]
 dist[447]
 dist[448]
 dist[449]
 dist[450]

In [97]:
@objective(model, Max, sum(dist[i] for i=1:M))

dist[1] + dist[2] + dist[3] + dist[4] + dist[5] + dist[6] + dist[7] + dist[8] + dist[9] + dist[10] + dist[11] + dist[12] + dist[13] + dist[14] + dist[15] + dist[16] + dist[17] + dist[18] + dist[19] + dist[20] + dist[21] + dist[22] + dist[23] + dist[24] + dist[25] + dist[26] + dist[27] + dist[28] + dist[29] + dist[30] + dist[31] + dist[32] + dist[33] + dist[34] + dist[35] + dist[36] + dist[37] + dist[38] + dist[39] + dist[40] + dist[41] + dist[42] + dist[43] + dist[44] + dist[45] + dist[46] + dist[47] + dist[48] + dist[49] + dist[50] + dist[51] + dist[52] + dist[53] + dist[54] + dist[55] + dist[56] + dist[57] + dist[58] + dist[59] + dist[60] + dist[61] + dist[62] + dist[63] + dist[64] + dist[65] + dist[66] + dist[67] + dist[68] + dist[69] + dist[70] + dist[71] + dist[72] + dist[73] + dist[74] + dist[75] + dist[76] + dist[77] + dist[78] + dist[79] + dist[80] + dist[81] + dist[82] + dist[83] + dist[84] + dist[85] + dist[86] + dist[87] + dist[88] + dist[89] + dist[90] + dist[91] + dist[92]

In [99]:
@constraints(model, begin
        sum(x[i] for i = 1:L) <= l
        [i = 1:M, j = 1:L], dist[i] <= x[j] * d[i,j] + (1-x[j]) * maximum(d)
        [i = 1:M], dist[i] >= 0
        end)

model

In [102]:
@time solve(model)

  0.841379 seconds (1.87 k allocations: 10.968 MiB)


:Optimal

In [103]:
getobjectivevalue(model)

50400.0

In [96]:
getobjectivevalue(model)

50400.0

In [111]:
?help

search: schedule @schedule hankelh2 hankelh1 hankelh2x hankelh1x Channel



**Welcome to Julia 0.6.2.** The full manual is available at

```
https://docs.julialang.org/
```

as well many great tutorials and learning resources:

```
https://julialang.org/learning/
```

For help on a specific function or macro, type `?` followed by its name, e.g. `?fft`, or `?@time`, and press enter.


In [112]:
?shuffle

search: shuffle shuffle!



```
shuffle([rng=GLOBAL_RNG,] v)
```

Return a randomly permuted copy of `v`. The optional `rng` argument specifies a random number generator (see [Random Numbers](@ref)). To permute `v` in-place, see [`shuffle!`](@ref).  To obtain randomly permuted indices, see [`randperm`](@ref).

# Example

```jldoctest
julia> rng = MersenneTwister(1234);

julia> shuffle(rng, collect(1:10))
10-element Array{Int64,1}:
  6
  1
 10
  2
  3
  9
  5
  7
  4
  8
```


In [126]:
shuffle(1:4)[1:2]

2-element Array{Int64,1}:
 3
 4